org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:/Program Files/Java/jdk-20.0.2
org.gradle.internal.http.connectionTimeout=60000
org.gradle.internal.http.socketTimeout=60000
android.suppressUnsupportedCompileSdk=34
